version: '3.8'

services:
  api:
    build: .
    depends_on:
      - db
    environment:
        STAGE: test
        SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    volumes:
      - ./app:/usr/src/app/
      - ./migrations:/usr/src/app/migrations
    ports:
      - 5000:5000

  db:
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
